// =======================
//  CATEGORY LIST (50x)
// =======================
export const categoriesData = [
  { id: 1, name: "Vitamin & Multivitamin" },
  { id: 2, name: "Batuk & Pilek" },
  { id: 3, name: "Demam & Nyeri" },
  { id: 4, name: "Asam Lambung / GERD" },
  { id: 5, name: "Alergi" },
  { id: 6, name: "Antibiotik" },
  { id: 7, name: "Kulit & Jamur" },
  { id: 8, name: "Pencernaan" },
  { id: 9, name: "Suplement Herbal" },
  { id: 10, name: "Diabetes" },
  { id: 11, name: "Hipertensi" },
  { id: 12, name: "Kolesterol" },
  { id: 13, name: "Kesehatan Mata" },
  { id: 14, name: "Kesehatan Telinga" },
  { id: 15, name: "Kesehatan Mulut" },
  { id: 16, name: "Kesehatan Wanita" },
  { id: 17, name: "Kesehatan Pria" },
  { id: 18, name: "Kehamilan & Menyusui" },
  { id: 19, name: "Anak - Anak" },
  { id: 20, name: "Obat Luar" },
  { id: 21, name: "Suplemen Daya Tahan Tubuh" },
  { id: 22, name: "Vitamin C" },
  { id: 23, name: "Vitamin B Kompleks" },
  { id: 24, name: "Obat Flu Dewasa" },
  { id: 25, name: "Obat Flu Anak" },
  { id: 26, name: "Pencernaan Anak" },
  { id: 27, name: "Antiseptik" },
  { id: 28, name: "Perban & Plester" },
  { id: 29, name: "Alat Kesehatan" },
  { id: 30, name: "Minyak Gosok" },
  { id: 31, name: "Obat Tidur / Stress" },
  { id: 32, name: "Obat Maag" },
  { id: 33, name: "Anti Radang" },
  { id: 34, name: "Penghilang Nyeri" },
  { id: 35, name: "Antijamur Kulit" },
  { id: 36, name: "Obat Sariawan" },
  { id: 37, name: "Obat Sakit Kepala" },
  { id: 38, name: "Obat Luka" },
  { id: 39, name: "Suplement Mineral" },
  { id: 40, name: "Suplemen Ibu Hamil" },
  { id: 41, name: "Obat Asma" },
  { id: 42, name: "Obat Tetes Mata" },
  { id: 43, name: "Obat Antibiotik Kulit" },
  { id: 44, name: "Obat Jerawat" },
  { id: 45, name: "Antiseptik Anak" },
  { id: 46, name: "Vitamin Anak" },
  { id: 47, name: "Tolak Angin / Masuk Angin" },
  { id: 48, name: "Suplemen Stamina" },
  { id: 49, name: "Obat Batuk Herbal" },
  { id: 50, name: "Obat Sakit Tenggorokan" },
];

// =======================
//   PRODUCT LIST (50x)
// =======================
export const productsData = [
  {
    id: 1,
    name: "Imboost Tablet",
    category: "Vitamin & Multivitamin",
    price: 38000,
    stock: 50,
  },
  {
    id: 2,
    name: "Imboost Force",
    category: "Vitamin & Multivitamin",
    price: 75000,
    stock: 30,
    promo: {
      enabled: true,
      type: "percent",
      value: 20,
      startDate: "2025-12-01",
      endDate: "2025-12-31",
    },
  },
  {
    id: 3,
    name: "Paracetamol 500mg",
    category: "Demam & Nyeri",
    price: 8000,
    stock: 100,
  },
  {
    id: 4,
    name: "Sanmol Syrup",
    category: "Demam & Nyeri",
    price: 18000,
    stock: 40,
  },
  {
    id: 5,
    name: "OBH Combi Anak",
    category: "Batuk & Pilek",
    price: 23000,
    stock: 25,
  },
  {
    id: 6,
    name: "OBH Combi Dewasa",
    category: "Batuk & Pilek",
    price: 26000,
    stock: 35,
  },
  {
    id: 7,
    name: "Panadol Extra",
    category: "Penghilang Nyeri",
    price: 14000,
    stock: 80,
  },
  {
    id: 8,
    name: "Procold Flu",
    category: "Obat Flu Dewasa",
    price: 7000,
    stock: 90,
  },
  { id: 9, name: "Promag", category: "Maag", price: 13000, stock: 50 },
  {
    id: 10,
    name: "Mylanta Cair",
    category: "Asam Lambung / GERD",
    price: 28000,
    stock: 30,
  },
  {
    id: 11,
    name: "Tolak Angin",
    category: "Tolak Angin / Masuk Angin",
    price: 3500,
    stock: 150,
  },
  {
    id: 12,
    name: "Vicks Vaporub",
    category: "Obat Luar",
    price: 29000,
    stock: 40,
  },
  {
    id: 13,
    name: "Betadine Antiseptic",
    category: "Antiseptik",
    price: 20000,
    stock: 25,
  },
  {
    id: 14,
    name: "Benoson Cream",
    category: "Obat Antibiotik Kulit",
    price: 16000,
    stock: 20,
  },
  {
    id: 15,
    name: "Ketoconazole Cream",
    category: "Antijamur Kulit",
    price: 17000,
    stock: 20,
  },
  {
    id: 16,
    name: "New Diatabs",
    category: "Pencernaan",
    price: 14000,
    stock: 50,
  },
  { id: 17, name: "Oralit", category: "Pencernaan", price: 5000, stock: 60 },
  {
    id: 18,
    name: "Sangobion",
    category: "Vitamin & Multivitamin",
    price: 18000,
    stock: 40,
  },
  {
    id: 19,
    name: "Hemaviton Action",
    category: "Suplemen Stamina",
    price: 15000,
    stock: 50,
  },
  {
    id: 20,
    name: "Bodrex Migra",
    category: "Obat Sakit Kepala",
    price: 8000,
    stock: 70,
  },
  {
    id: 21,
    name: "Neuralgin",
    category: "Anti Radang",
    price: 17000,
    stock: 60,
  },
  {
    id: 22,
    name: "Mucopect",
    category: "Batuk & Pilek",
    price: 40000,
    stock: 30,
  },
  {
    id: 23,
    name: "Siladex Merah",
    category: "Batuk & Pilek",
    price: 18000,
    stock: 40,
  },
  { id: 24, name: "Entrostop", category: "Pencernaan", price: 9000, stock: 80 },
  {
    id: 25,
    name: "Mixagrip",
    category: "Obat Flu Dewasa",
    price: 6000,
    stock: 100,
  },
  {
    id: 26,
    name: "Termorex Syrup",
    category: "Demam & Nyeri",
    price: 18000,
    stock: 35,
  },
  {
    id: 27,
    name: "Insto Dry Eyes",
    category: "Kesehatan Mata",
    price: 14000,
    stock: 35,
  },
  {
    id: 28,
    name: "Dermatix Gel",
    category: "Obat Luka",
    price: 250000,
    stock: 10,
    promo: {
      enabled: true,
      type: "fixed",
      value: 20000,
      startDate: "2025-12-01",
      endDate: "2025-12-15",
    },
  },
  {
    id: 29,
    name: "Betadine Mouthwash",
    category: "Kesehatan Mulut",
    price: 27000,
    stock: 20,
  },
  {
    id: 30,
    name: "Antangin JRG",
    category: "Tolak Angin / Masuk Angin",
    price: 5000,
    stock: 80,
  },
  {
    id: 31,
    name: "Decolgen",
    category: "Obat Flu Dewasa",
    price: 7000,
    stock: 70,
  },
  { id: 32, name: "Salep 88", category: "Obat Luar", price: 12000, stock: 50 },
  {
    id: 33,
    name: "Counterpain",
    category: "Minyak Gosok",
    price: 38000,
    stock: 40,
  },
  {
    id: 34,
    name: "Minyak Kayu Putih",
    category: "Minyak Gosok",
    price: 15000,
    stock: 100,
  },
  {
    id: 35,
    name: "Freshcare",
    category: "Minyak Gosok",
    price: 13000,
    stock: 80,
  },
  {
    id: 36,
    name: "OBH Herbal",
    category: "Obat Batuk Herbal",
    price: 20000,
    stock: 40,
  },
  {
    id: 37,
    name: "Komix Herbal",
    category: "Obat Batuk Herbal",
    price: 6000,
    stock: 120,
  },
  { id: 38, name: "Enervon C", category: "Vitamin C", price: 35000, stock: 40 },
  {
    id: 39,
    name: "Becom C",
    category: "Vitamin B Kompleks",
    price: 26000,
    stock: 60,
  },
  {
    id: 40,
    name: "Curcuma Plus",
    category: "Vitamin Anak",
    price: 30000,
    stock: 25,
  },
  {
    id: 41,
    name: "Zinc Tablet",
    category: "Suplement Mineral",
    price: 8000,
    stock: 70,
  },
  {
    id: 42,
    name: "Hydro Coco",
    category: "Suplement Mineral",
    price: 9000,
    stock: 100,
  },
  {
    id: 43,
    name: "Orikids",
    category: "Vitamin Anak",
    price: 26000,
    stock: 30,
  },
  {
    id: 44,
    name: "Insto Regular",
    category: "Kesehatan Mata",
    price: 15000,
    stock: 20,
  },
  {
    id: 45,
    name: "My Baby Minyak Telon",
    category: "Anak - Anak",
    price: 18000,
    stock: 60,
  },
  {
    id: 46,
    name: "Minyak Telon Konicare",
    category: "Anak - Anak",
    price: 22000,
    stock: 40,
  },
  {
    id: 47,
    name: "Hansaplast",
    category: "Perban & Plester",
    price: 6000,
    stock: 200,
  },
  {
    id: 48,
    name: "Plester Koyo",
    category: "Obat Luar",
    price: 8000,
    stock: 120,
  },
  {
    id: 49,
    name: "Cataflam",
    category: "Anti Radang",
    price: 32000,
    stock: 50,
  },
  {
    id: 50,
    name: "Voltaren Gel",
    category: "Obat Luar",
    price: 50000,
    stock: 30,
  },
];

// =======================
//   CUSTOMER LIST (50x)
// =======================
export const customersData = [
  {
    id: 1,
    name: "John Doe",
    phone: "081234567890",
    email: "john.doe@example.com",
    username: "johndoe",
    alamat: "Jl. Merpati No. 1",
  },
  {
    id: 2,
    name: "Sarah Smith",
    phone: "081234567891",
    email: "sarah.smith@example.com",
    username: "sarahsmith",
    alamat: "Jl. Kenanga No. 2",
  },
  {
    id: 3,
    name: "Michael Andrew",
    phone: "081234567892",
    email: "michael.andrew@example.com",
    username: "michaelandrew",
    alamat: "Jl. Mawar No. 3",
  },
  {
    id: 4,
    name: "Laura Kin",
    phone: "081234567893",
    email: "laura.kin@example.com",
    username: "laurakin",
    alamat: "Jl. Melati No. 4",
  },
  {
    id: 5,
    name: "Kevin Hart",
    phone: "081234567894",
    email: "kevin.hart@example.com",
    username: "kevinhart",
    alamat: "Jl. Teratai No. 5",
  },
  {
    id: 6,
    name: "Maria Jones",
    phone: "081234567895",
    email: "maria.jones@example.com",
    username: "mariajones",
    alamat: "Jl. Dahlia No. 6",
  },
  {
    id: 7,
    name: "Nathan Gray",
    phone: "081234567896",
    email: "nathan.gray@example.com",
    username: "nathangray",
    alamat: "Jl. Cempaka No. 7",
  },
  {
    id: 8,
    name: "Emma Watson",
    phone: "081234567897",
    email: "emma.watson@example.com",
    username: "emmawatson",
    alamat: "Jl. Flamboyan No. 8",
  },
  {
    id: 9,
    name: "George Miller",
    phone: "081234567898",
    email: "george.miller@example.com",
    username: "georgemiller",
    alamat: "Jl. Sakura No. 9",
  },
  {
    id: 10,
    name: "Angela Ray",
    phone: "081234567899",
    email: "angela.ray@example.com",
    username: "angelaray",
    alamat: "Jl. Cemara No. 10",
  },
  {
    id: 11,
    name: "Daniel Cooper",
    phone: "081234567800",
    email: "daniel.cooper@example.com",
    username: "danielcooper",
    alamat: "Jl. Kaktus No. 11",
  },
  {
    id: 12,
    name: "Sophia Turner",
    phone: "081234567801",
    email: "sophia.turner@example.com",
    username: "sophiaturner",
    alamat: "Jl. Meranti No. 12",
  },
  {
    id: 13,
    name: "Oliver Clark",
    phone: "081234567802",
    email: "oliver.clark@example.com",
    username: "oliverclark",
    alamat: "Jl. Jati No. 13",
  },
  {
    id: 14,
    name: "Ella Brown",
    phone: "081234567803",
    email: "ella.brown@example.com",
    username: "ellabrown",
    alamat: "Jl. Pinus No. 14",
  },
  {
    id: 15,
    name: "James Gordon",
    phone: "081234567804",
    email: "james.gordon@example.com",
    username: "jamesgordon",
    alamat: "Jl. Nangka No. 15",
  },
  {
    id: 16,
    name: "Isabella Lee",
    phone: "081234567805",
    email: "isabella.lee@example.com",
    username: "isabellalee",
    alamat: "Jl. Manggis No. 16",
  },
  {
    id: 17,
    name: "Henry Wilson",
    phone: "081234567806",
    email: "henry.wilson@example.com",
    username: "henrywilson",
    alamat: "Jl. Sawo No. 17",
  },
  {
    id: 18,
    name: "Ava Martinez",
    phone: "081234567807",
    email: "ava.martinez@example.com",
    username: "avamartinez",
    alamat: "Jl. Durian No. 18",
  },
  {
    id: 19,
    name: "Matthew Walker",
    phone: "081234567808",
    email: "matthew.walker@example.com",
    username: "matthewwalker",
    alamat: "Jl. Kedondong No. 19",
  },
  {
    id: 20,
    name: "Chloe Davis",
    phone: "081234567809",
    email: "chloe.davis@example.com",
    username: "chloedavis",
    alamat: "Jl. Ketapang No. 20",
  },
  {
    id: 21,
    name: "Jack Ryan",
    phone: "081234567810",
    email: "jack.ryan@example.com",
    username: "jackryan",
    alamat: "Jl. Karet No. 21",
  },
  {
    id: 22,
    name: "Olivia King",
    phone: "081234567811",
    email: "olivia.king@example.com",
    username: "oliviaking",
    alamat: "Jl. Anggrek No. 22",
  },
  {
    id: 23,
    name: "William Scott",
    phone: "081234567812",
    email: "william.scott@example.com",
    username: "williamscott",
    alamat: "Jl. Kenari No. 23",
  },
  {
    id: 24,
    name: "Emily Lewis",
    phone: "081234567813",
    email: "emily.lewis@example.com",
    username: "emilylewis",
    alamat: "Jl. Rambutan No. 24",
  },
  {
    id: 25,
    name: "David Harris",
    phone: "081234567814",
    email: "david.harris@example.com",
    username: "davidharris",
    alamat: "Jl. Pepaya No. 25",
  },
  {
    id: 26,
    name: "Mia Carter",
    phone: "081234567815",
    email: "mia.carter@example.com",
    username: "miacarter",
    alamat: "Jl. Mangga No. 26",
  },
  {
    id: 27,
    name: "Andrew Hall",
    phone: "081234567816",
    email: "andrew.hall@example.com",
    username: "andrewhall",
    alamat: "Jl. Apel No. 27",
  },
  {
    id: 28,
    name: "Grace Allen",
    phone: "081234567817",
    email: "grace.allen@example.com",
    username: "graceallen",
    alamat: "Jl. Pisang No. 28",
  },
  {
    id: 29,
    name: "Samuel Baker",
    phone: "081234567818",
    email: "samuel.baker@example.com",
    username: "samuelbaker",
    alamat: "Jl. Melon No. 29",
  },
  {
    id: 30,
    name: "Victoria Brooks",
    phone: "081234567819",
    email: "victoria.brooks@example.com",
    username: "victoriabrooks",
    alamat: "Jl. Pepaya No. 30",
  },
  {
    id: 31,
    name: "Ryan Flores",
    phone: "081234567820",
    email: "ryan.flores@example.com",
    username: "ryanflores",
    alamat: "Jl. Mawar No. 31",
  },
  {
    id: 32,
    name: "Bella Ross",
    phone: "081234567821",
    email: "bella.ross@example.com",
    username: "bellaross",
    alamat: "Jl. Cempaka No. 32",
  },
  {
    id: 33,
    name: "Ethan Gray",
    phone: "081234567822",
    email: "ethan.gray@example.com",
    username: "ethangray",
    alamat: "Jl. Teratai No. 33",
  },
  {
    id: 34,
    name: "Zoe Rivera",
    phone: "081234567823",
    email: "zoe.rivera@example.com",
    username: "zoerivera",
    alamat: "Jl. Melati No. 34",
  },
  {
    id: 35,
    name: "Adam Reed",
    phone: "081234567824",
    email: "adam.reed@example.com",
    username: "adamreed",
    alamat: "Jl. Sakura No. 35",
  },
  {
    id: 36,
    name: "Natalie Cox",
    phone: "081234567825",
    email: "natalie.cox@example.com",
    username: "nataliecox",
    alamat: "Jl. Kenanga No. 36",
  },
  {
    id: 37,
    name: "Joseph Ward",
    phone: "081234567826",
    email: "joseph.ward@example.com",
    username: "josephward",
    alamat: "Jl. Soka No. 37",
  },
  {
    id: 38,
    name: "Hannah Price",
    phone: "081234567827",
    email: "hannah.price@example.com",
    username: "hannahprice",
    alamat: "Jl. Jati No. 38",
  },
  {
    id: 39,
    name: "Liam Richardson",
    phone: "081234567828",
    email: "liam.richardson@example.com",
    username: "liamrichardson",
    alamat: "Jl. Kamboja No. 39",
  },
  {
    id: 40,
    name: "Ariana Perry",
    phone: "081234567829",
    email: "ariana.perry@example.com",
    username: "arianaperry",
    alamat: "Jl. Karet No. 40",
  },
  {
    id: 41,
    name: "Lucas Butler",
    phone: "081234567830",
    email: "lucas.butler@example.com",
    username: "lucasbutler",
    alamat: "Jl. Mawar No. 41",
  },
  {
    id: 42,
    name: "Scarlett Adams",
    phone: "081234567831",
    email: "scarlett.adams@example.com",
    username: "scarlettadams",
    alamat: "Jl. Cemara No. 42",
  },
  {
    id: 43,
    name: "Nathan Bennett",
    phone: "081234567832",
    email: "nathan.bennett@example.com",
    username: "nathanbennett",
    alamat: "Jl. Pinus No. 43",
  },
  {
    id: 44,
    name: "Lily Foster",
    phone: "081234567833",
    email: "lily.foster@example.com",
    username: "lilyfoster",
    alamat: "Jl. Anggrek No. 44",
  },
  {
    id: 45,
    name: "Chris Morgan",
    phone: "081234567834",
    email: "chris.morgan@example.com",
    username: "chrismorgan",
    alamat: "Jl. Kenari No. 45",
  },
  {
    id: 46,
    name: "Amelia Gray",
    phone: "081234567835",
    email: "amelia.gray@example.com",
    username: "ameliagray",
    alamat: "Jl. Melon No. 46",
  },
  {
    id: 47,
    name: "David Collins",
    phone: "081234567836",
    email: "david.collins@example.com",
    username: "davidcollins",
    alamat: "Jl. Apel No. 47",
  },
  {
    id: 48,
    name: "Ella Sanders",
    phone: "081234567837",
    email: "ella.sanders@example.com",
    username: "ellasanders",
    alamat: "Jl. Pisang No. 48",
  },
  {
    id: 49,
    name: "Michael Evans",
    phone: "081234567838",
    email: "michael.evans@example.com",
    username: "michaelevans",
    alamat: "Jl. Pepaya No. 49",
  },
  {
    id: 50,
    name: "Sofia Cooper",
    phone: "081234567839",
    email: "sofia.cooper@example.com",
    username: "sofiacooper",
    alamat: "Jl. Mangga No. 50",
  },
];

export const ordersData = [
  {
    id: 1,
    orderId: "ORD-001",
    invoiceNumber: "INV-0001",
    customer: "Budi",
    alamat: "Jl. Merpati No. 12",
    noHp: "081234567801",
    status: "paid",
    paymentMethod: "cash",
    items: [
      { productId: 3, qty: 2, price: 8000 },
      { productId: 17, qty: 1, price: 5000 },
    ],
  },
  {
    id: 2,
    orderId: "ORD-002",
    invoiceNumber: "INV-0002",
    customer: "Sari",
    alamat: "Jl. Kenanga No. 9",
    noHp: "081234567802",
    status: "shipping",
    resi: "TRK-002-12345",
    paymentMethod: "qris",
    items: [
      { productId: 1, qty: 1, price: 38000 },
      { productId: 2, qty: 1, price: 75000 },
    ],
  },
  {
    id: 3,
    orderId: "ORD-003",
    invoiceNumber: "INV-0003",
    customer: "Dewi",
    alamat: "Jl. Mawar No. 5",
    noHp: "081234567803",
    status: "success",
    paymentMethod: "transfer",
    items: [{ productId: 11, qty: 3, price: 3500 }],
  },
  {
    id: 4,
    orderId: "ORD-004",
    invoiceNumber: "INV-0004",
    customer: "Andi",
    alamat: "Jl. Anggrek No. 21",
    noHp: "081234567804",
    status: "pending",
    paymentMethod: "cash",
    items: [
      { productId: 7, qty: 1, price: 14000 },
      { productId: 31, qty: 2, price: 7000 },
    ],
  },
  {
    id: 5,
    orderId: "ORD-005",
    invoiceNumber: "INV-0005",
    customer: "Rina",
    alamat: "Jl. Melati No. 2",
    noHp: "081234567805",
    status: "canceled",
    paymentMethod: "qris",
    items: [{ productId: 38, qty: 1, price: 35000 }],
  },
  {
    id: 6,
    orderId: "ORD-006",
    invoiceNumber: "INV-0006",
    customer: "Joko",
    alamat: "Jl. Dahlia No. 33",
    noHp: "081234567806",
    status: "success",
    paymentMethod: "cash",
    items: [{ productId: 20, qty: 3, price: 8000 }],
  },
  {
    id: 7,
    orderId: "ORD-007",
    invoiceNumber: "INV-0007",
    customer: "Putri",
    alamat: "Jl. Soka No. 18",
    noHp: "081234567807",
    status: "shipping",
    resi: "TRK-007-99881",
    paymentMethod: "transfer",
    items: [
      { productId: 5, qty: 1, price: 23000 },
      { productId: 6, qty: 1, price: 26000 },
    ],
  },
  {
    id: 8,
    orderId: "ORD-008",
    invoiceNumber: "INV-0008",
    customer: "Bayu",
    alamat: "Jl. Teratai No. 11",
    noHp: "081234567808",
    status: "pending",
    paymentMethod: "cash",
    items: [{ productId: 12, qty: 1, price: 29000 }],
  },
  {
    id: 9,
    orderId: "ORD-009",
    invoiceNumber: "INV-0009",
    customer: "Dian",
    alamat: "Jl. Flamboyan No. 7",
    noHp: "081234567809",
    status: "paid",
    paymentMethod: "qris",
    items: [{ productId: 8, qty: 4, price: 7000 }],
  },
  {
    id: 10,
    orderId: "ORD-010",
    invoiceNumber: "INV-0010",
    customer: "Farhan",
    alamat: "Jl. Pala No. 13",
    noHp: "081234567810",
    status: "success",
    paymentMethod: "cash",
    items: [
      { productId: 9, qty: 1, price: 13000 },
      { productId: 24, qty: 2, price: 9000 },
    ],
  },
  {
    id: 11,
    orderId: "ORD-011",
    invoiceNumber: "INV-0011",
    customer: "Sinta",
    alamat: "Jl. Rajawali No. 12",
    noHp: "081234567811",
    status: "canceled",
    paymentMethod: "transfer",
    items: [{ productId: 10, qty: 1, price: 28000 }],
  },
  {
    id: 12,
    orderId: "ORD-012",
    invoiceNumber: "INV-0012",
    customer: "Rudi",
    alamat: "Jl. Mangga No. 51",
    noHp: "081234567812",
    status: "success",
    paymentMethod: "cash",
    items: [
      { productId: 13, qty: 1, price: 20000 },
      { productId: 47, qty: 1, price: 6000 },
    ],
  },
  {
    id: 13,
    orderId: "ORD-013",
    invoiceNumber: "INV-0013",
    customer: "Lina",
    alamat: "Jl. Kelapa No. 44",
    noHp: "081234567813",
    status: "paid",
    paymentMethod: "qris",
    items: [{ productId: 18, qty: 2, price: 18000 }],
  },
  {
    id: 14,
    orderId: "ORD-014",
    invoiceNumber: "INV-0014",
    customer: "Hendra",
    alamat: "Jl. Belimbing No. 3",
    noHp: "081234567814",
    status: "pending",
    paymentMethod: "cash",
    items: [{ productId: 33, qty: 1, price: 38000 }],
  },
  {
    id: 15,
    orderId: "ORD-015",
    invoiceNumber: "INV-0015",
    customer: "Ajeng",
    alamat: "Jl. Cemara No. 10",
    noHp: "081234567815",
    status: "process",
    paymentMethod: "transfer",
    items: [
      { productId: 21, qty: 2, price: 17000 },
      { productId: 49, qty: 1, price: 32000 },
    ],
  },
  {
    id: 16,
    orderId: "ORD-016",
    invoiceNumber: "INV-0016",
    customer: "Indra",
    alamat: "Jl. Jeruk No. 9",
    noHp: "081234567816",
    status: "success",
    paymentMethod: "qris",
    items: [{ productId: 23, qty: 1, price: 18000 }],
  },
  {
    id: 17,
    orderId: "ORD-017",
    invoiceNumber: "INV-0017",
    customer: "Nina",
    alamat: "Jl. Bougenville No. 6",
    noHp: "081234567817",
    status: "paid",
    paymentMethod: "cash",
    items: [
      { productId: 29, qty: 1, price: 27000 },
      { productId: 44, qty: 1, price: 15000 },
    ],
  },
  {
    id: 18,
    orderId: "ORD-018",
    invoiceNumber: "INV-0018",
    customer: "Agus",
    alamat: "Jl. Jambu No. 17",
    noHp: "081234567818",
    status: "success",
    paymentMethod: "transfer",
    items: [{ productId: 28, qty: 1, price: 250000 }],
  },
  {
    id: 19,
    orderId: "ORD-019",
    invoiceNumber: "INV-0019",
    customer: "Salsa",
    alamat: "Jl. Pinang No. 22",
    noHp: "081234567819",
    status: "shipping",
    resi: "TRK-019-66774",
    paymentMethod: "cash",
    items: [{ productId: 47, qty: 3, price: 6000 }],
  },
  {
    id: 20,
    orderId: "ORD-020",
    invoiceNumber: "INV-0020",
    customer: "Tono",
    alamat: "Jl. Nangka No. 77",
    noHp: "081234567820",
    status: "pending",
    paymentMethod: "qris",
    items: [
      { productId: 45, qty: 1, price: 18000 },
      { productId: 46, qty: 1, price: 22000 },
    ],
  },
  {
    id: 21,
    orderId: "ORD-021",
    invoiceNumber: "INV-0021",
    customer: "Wati",
    alamat: "Jl. Kenari No. 19",
    noHp: "081234567821",
    status: "canceled",
    paymentMethod: "transfer",
    items: [{ productId: 40, qty: 1, price: 30000 }],
  },
  {
    id: 22,
    orderId: "ORD-022",
    invoiceNumber: "INV-0022",
    customer: "Rio",
    alamat: "Jl. Sawo No. 88",
    noHp: "081234567822",
    status: "success",
    paymentMethod: "cash",
    items: [
      { productId: 37, qty: 2, price: 6000 },
      { productId: 25, qty: 2, price: 6000 },
    ],
  },
  {
    id: 23,
    orderId: "ORD-023",
    invoiceNumber: "INV-0023",
    customer: "Mega",
    alamat: "Jl. Ketapang No. 55",
    noHp: "081234567823",
    status: "paid",
    paymentMethod: "qris",
    items: [{ productId: 22, qty: 1, price: 40000 }],
  },
  {
    id: 24,
    orderId: "ORD-024",
    invoiceNumber: "INV-0024",
    customer: "Yoga",
    alamat: "Jl. Matahari No. 4",
    noHp: "081234567824",
    status: "pending",
    paymentMethod: "cash",
    items: [
      { productId: 15, qty: 1, price: 17000 },
      { productId: 14, qty: 1, price: 16000 },
    ],
  },
  {
    id: 25,
    orderId: "ORD-025",
    invoiceNumber: "INV-0025",
    customer: "Vina",
    alamat: "Jl. Pelangi No. 99",
    noHp: "081234567825",
    status: "success",
    paymentMethod: "transfer",
    items: [{ productId: 16, qty: 1, price: 14000 }],
  },
  {
    id: 26,
    orderId: "ORD-026",
    invoiceNumber: "INV-0026",
    customer: "Eka",
    alamat: "Jl. Sakura No. 61",
    noHp: "081234567826",
    status: "process",
    paymentMethod: "cash",
    items: [{ productId: 19, qty: 2, price: 15000 }],
  },
  {
    id: 27,
    orderId: "ORD-027",
    invoiceNumber: "INV-0027",
    customer: "Hilmi",
    alamat: "Jl. Melon No. 12",
    noHp: "081234567827",
    status: "paid",
    paymentMethod: "qris",
    items: [
      { productId: 27, qty: 1, price: 14000 },
      { productId: 44, qty: 1, price: 15000 },
    ],
  },
  {
    id: 28,
    orderId: "ORD-028",
    invoiceNumber: "INV-0028",
    customer: "Nabila",
    alamat: "Jl. Sawo Kecil No. 8",
    noHp: "081234567828",
    status: "canceled",
    paymentMethod: "transfer",
    items: [{ productId: 26, qty: 1, price: 18000 }],
  },
  {
    id: 29,
    orderId: "ORD-029",
    invoiceNumber: "INV-0029",
    customer: "Tama",
    alamat: "Jl. Pisang No. 2",
    noHp: "081234567829",
    status: "success",
    paymentMethod: "cash",
    items: [{ productId: 39, qty: 1, price: 26000 }],
  },
  {
    id: 30,
    orderId: "ORD-030",
    invoiceNumber: "INV-0030",
    customer: "Sela",
    alamat: "Jl. Cendana No. 17",
    noHp: "081234567830",
    status: "paid",
    paymentMethod: "qris",
    items: [{ productId: 35, qty: 2, price: 13000 }],
  },
];

export const usersData = [
  {
    id: 1,
    name: "Super Admin",
    email: "superadmin@system.com",
    phone: "081210000001",
    role: "superadmin",
    permissions: {
      dashboard: { create: true, read: true, update: true, delete: true },
      product: { create: true, read: true, update: true, delete: true },
      order: { create: true, read: true, update: true, delete: true },
      purchase: { create: true, read: true, update: true, delete: true },
      expense: { create: true, read: true, update: true, delete: true },
      report: { create: true, read: true, update: true, delete: true },
    },
  },
  {
    id: 2,
    name: "Admin Operasional",
    email: "admin.ops@system.com",
    phone: "081210000002",
    role: "admin",
    // override example: disallow creating products even though admin role has full perms
    permissions: { product: { create: false } },
  },

  {
    id: 3,
    name: "Apotek Kimia Farma Online",
    email: "kf.online@shop.com",
    phone: "081210000003",
    role: "seller_owner",
    permissions: {},
  },

  {
    id: 4,
    name: "Staff Apotek Kimia Farma Online",
    email: "admin.kfonline@shop.com",
    phone: "081210000004",
    role: "seller_staff",
    permissions: {},
  },

  {
    id: 5,
    name: "Kasir Apotek Kimia Farma Online",
    email: "kasirA.kfonline@shop.com",
    phone: "081210000005",
    role: "seller_staff",
    // override example: allow product create for this specific user
    permissions: { product: { create: true } },
  },

  {
    id: 6,
    name: "Gudang Apotek Kimia Farma Online",
    email: "gudang.kfonline@shop.com",
    phone: "081210000006",
    role: "warehouse",
    permissions: {},
  },
];
